### ISSUE TITLE
using async request in $transitions ( new senario )

### ISSUE THREAD

**Issue by imansarhaddi** [ui-router/core#110]
Hi guys

i have a $transition.onBefore with a async request, note that i don't want the transition to be wait for the response.
i just want the transition does its way as the request does.
here is my question: as i have async request, we have 2 states,
1: response will return when the transition is not complete(assume it is posible), and is within one the proccess such as onEnter, onStart, onExit and so on...
2: response will return when the transition is complete
so what should i do?
should i use transition.router.stateServices.target('login') or $state.go('login') or something else?
and if i use one of them what's wrong with the transition?
i thought if use transition.router.stateServices.target('login') and the transition is not complete, it will change the target anf everything is ok (meybe is not if it passed onBefore 
or if is onStart step or somehow...)
but if the transition is complete it goes wrong and can't change the target beacuse the transition is finished.
and if i use $state.go when the transition is not complete the transition will suppersend and is not ok, but if the transition is complete $state.go('login') is ok to use.

my code:

```
.run(['localStorageService', 'AuthenticationService', '$transitions', function('localStorageService', 'AuthenticationService', '$transitions') {
 $transitions.onBefore({to: 'main.**'//means every route except login}, function(transition) {
  var userAuth = locationStorageService.get('userAuth');
  if (!userAuth || isExpired()) {
   return transition.router.stateServices.target('login');
  }
  
  AuthenticationService.isAuthorized(userAuth.username, function(result) {
   if (false === result) {
    return transition.router.stateServices.target('login');// or $state.go('login')
   }
  })
  
  function isExpired () {
   return Date.now() > userAuth.expirationTime;
  }
 }
 
}]);
```
here is my factory

```
.factory('AuthenticationService', function($http) {
 var service;
 service.isAuthorized = isAuthorized;
 return service;
 
 function isAuthorized (username, callback) {
  $http.post(url, data).then(
   function(response) {
    if (0 !== response.status){
     callback(false);
    }
   }, function(response) {
    callback(false);
   }
  );
 }
});
```
@christopherthielen

Thanks for your rapid replies ;-)

**Comment by christopherthielen** [comment]
# cancel and send user to 'login'

Let's say you have a promise `loginPromise` for user authentication check:
You can start the async check in an onBefore hook.  When the promise is rejected (because the user is not authenticated), you can cancel the transition and send the user to `'login'`.

```js
    loginPromise.catch(err => {
      console.log('auth check failed; go to login')
      if (transition.isActive()) {
        transition.abort();
      }
      transition.router.stateService.go('login');
    });
```


## Example 1:
https://stackblitz.com/edit/ui-router-angularjs-lvkf9j?file=app.js

1) Click `'home'`
2) Type auth check delay of 3000
3) Click 'main'

Note that the transition is cancelled and the user ends up on `'login'`

1) Click `'home'`
2) Type auth check delay of 6000
3) Click 'main'

Note that the '`main'` state is activated, then the authentication promise completes and the user is sent to `'login'`

1) uncomment `// transition.onFinish({}, () => loginPromise);`
2) Click `'home'`
3) Type auth check delay of 6000
4) Click 'main'

Note that the `'main'` state was not activated because the `onFinish` hook waits for the login  promise to settle.
