### ISSUE TITLE
Suggest location: 'replace' on redirectTo behavior

### ISSUE THREAD

**Issue by ako977** [ui-router/core#13]
In UI Router < version 1.x, I had implemented my own redirectTo functionality in a $stateChangeStart event. One thing that I added was a 'replace' for the location parameter. eg.
`$state.go(toState.redirectTo, toStateParams, {location: 'replace'});`
The benefit of this was to avoid the odd glitch in browser history.

For eg. when a user navigates: `was on state1 -> (navigates) -> state 2 -> (redirect occurs) -> state3`
Then they click the back button in the browser.
With location: 'replace', they are taken to state 1, and skip state 2, which I think is a better experience.

With the built in redirectTo in UI Router version 1.x, this doesn't seem to be the case.
Clicking the back button causes a brief "blip", taking the user to state 2, and quickly redirecting back to state 3.
Upon clicking it again, only then are you taken to state 1 as expected.

Are there any plans to improve this? Or is there a work around to cause the "redirectTo" to perform a `location: 'replace'`?

**Comment by christopherthielen** [comment]
related: https://github.com/angular-ui/ui-router/issues/3187#issuecomment-267198533

Yes, I'd like to address this issue.

Note that we have to be smart about when to use/not use replace.  We should only use replace if the router is *responding* to a browser url change.  We should not use replace if the transition was initiated using `$state.go()` for instance.  Here is why:


### router responds to URL change

url changed to `/A` -> find ui-router state 'A' -> begin transition -> redirect to 'B' -> activate 'B' -> update URL with `{ location: 'replace' }`

The URL changed to `/A` due to either a `href` link clicked or a sync during the initial application load (for example, user clicked a bookmark).  Once we redirect to 'B', we don't want `/A` in the browser history, so replace is correct.

## router initiates transition via `$state.go()`

browser url is `/Z` -> click `ui-sref="A"` -> `$state.go('A')` -> begin transition -> redirect to 'B' -> activate 'B' -> update URL without `replace`

The browser URL is only updated [after a transition is successful](https://github.com/ui-router/core/blob/master/src/hooks/url.ts#L8-L31).  The url is never updated in response to the original transition to 'A'.  After redirecting and activating `B`, we don't want to use `replace` because it would clobber the `/Z` in the browser history.

---

### necessary changes

The code for this belongs in the [redirect building code](https://github.com/ui-router/core/blob/master/src/transition/transition.ts#L479-L480).  Given an existing `Transition` (to 'A') that should be redirected and a new target ('B'), this code creates a new `Transition` to 'B' based on the original Transition.

This new Transition's options could be set to `location: 'replace'` if the original Transition's was [started due to the url changing](https://github.com/ui-router/core/blob/master/src/state/stateQueueManager.ts#L115-L121).  I think checking for `options().source === 'url'` on the original Transition should be correct.

**Comment by ako977** [comment]
Ok I think I understand what you mean now with the concern on when to use `location: 'replace'`, however I'm curious, for the explanation on "router initiates transition via $state.go()" are you saying that's the current behavior in the version 1.x code now, or the behavior you would like to see? 

The reason I ask is because by the explanation:

> The browser URL is only updated after a transition is successful. The url is never updated in response to the original transition to 'A'.

I should not need to click the back button twice right now when a redirect occurs since the url would never have been updated in the browser for transition 'A'.

Your "necessary changes" suggestion would only apply to the first scenario "router responds to URL change" correct?

**Comment by christopherthielen** [comment]
> for the explanation on router initiates transition via $state.go() are you saying that's the current behavior in the version 1.x code now

That's the current behavior, and also how it should remain.

> I should not need to click the back button twice right now when a redirect occurs since the url would never have been updated in the browser for transition 'A'.

Correct.  In the case of a redirect initiated during a `$state.go()` (for example, via ui-sref), the back button should work today.  To see this in action, go here:  http://plnkr.co/edit/qnsRwES54qgUW35wloal?p=preview  Click `other` then click `home` -> redirects to `home.foo`.  Click back button and you arrive back at `/other`

> Your necessary changes suggestion would only apply to the first scenario router responds to URL change correct?

Correct.

**Comment by ako977** [comment]
After looking at my code, I think I know why I don't see the expected behavior you mentioned for `$state.go`, and it's that in some cases I am not using `$state.go`, and rather ng-href. I am guessing because the links are activated as regular URLs, then the url is not prevented from updating for transition 'A' before redirecting to transition 'B'.

So the next question is, would you consider **_non_** `ui-sref` and `$state.go` router changes (eg. links with ng-href or href) a "router responds to URL change"?

**Comment by ako977** [comment]
In fact aftger thinking about it some more, I would understand if you said links with href or ng-href behaved like "router responds to URL change". 

The reason being it is out of the ui router influence, this means ui router would only be aware of the changes via a URL change. Thus, it would behave like:

> url changed to /A -> find ui-router state 'A' -> begin transition -> redirect to 'B' -> activate 'B' -> update URL with { location: 'replace' }

Which then leads to the suggested change you requested for the code segment.
Hope I am on the right track

**Comment by christopherthielen** [comment]
> would you consider non ui-sref and $state.go router changes (eg. links with ng-href or href) a "router responds to URL change"?

Yes, anything which updated the URL (including href) is processed by angular which [broadcasts the `$locationChangeStart` event](https://github.com/angular/angular.js/blob/b77defde81fc265c13fa504dc78b41a43997abf4/src/ng/location.js#L970-L984).  the ng1 adapter code [listens for `$locationChangeSuccess`](https://github.com/angular-ui/ui-router/blob/8f3074e3a9912955b8f589e42943f410170570ac/src/ng1/services.ts#L188-L189) and then tells the [urlRouter to update](https://github.com/ui-router/core/blob/b64973694e77c85ff331b51fc9d10ff8e975b4fb/src/url/urlRouter.ts#L43-L65) (check each URL rule against the current URL, and invoke the callback for the matched rule).  When a state is matched, its rule calls `$state.go(matchedstate, matchedparams, { source: 'url' })` and informs that the state change was [triggered by a url change](https://github.com/ui-router/core/blob/master/src/state/stateQueueManager.ts#L120-L122).

**Comment by christopherthielen** [comment]
> Hope I am on the right track

Exactly!

**Comment by christopherthielen** [comment]
closed by 23e2b7895f57a0d5469ad9043e987d023d386b02
