### ISSUE TITLE
Double onEnter = Param values not valid for state ?

### ISSUE THREAD

**Issue by FGRibreau** [ui-router/core#18]
Hello !

### context 
I have one state A, a child B and a child C:

```
A -> B -> C
```

In state A declaration:

```js
name: 'organizations',
url: '/organizations',
onEnter: (trans, state) => {
      if (trans.params().organization_id) {
        return;
      }

      return trans.injector().getAsync('organizations').then(organizations => {
        const organization_id = get(organizations, '[0].organization_id');
        if (!organization_id) {
          return;
        }

          stateService.go(applications.state, {organization_id}); // will work
      });
    },
```

In state A.B declaration:

```js
parent: organizationsState,
name: 'applications',
url: '/:organization_id/applications',
onEnter: (trans) => {
      if (trans.params().application_id) {
        return;
      }

      return trans.injector().getAsync('applications').then(applications => {
        const application_id = get(applications, '[0].application_id');
        if (!application_id) {
          return;
        }

        stateService.go(sessions.state, {application_id}); // will throw a "Param values not valid for state" even if application_id is perfectly valid.
      });
    },
```

In state A.B.C declaration:

```js
parent: applicationState,
name: 'sessions',
url: '/:application_id/sessions',

// no params:{} or thing like that
```

### issue 

When transitioning from onEnter to onEnter callback using stateService.go() the second call will throw a "Param values not valid for state" even if application_id is perfectly valid.

### workaround

The workaround is to defer `stateService.go(sessions.state, {application_id});` with `setTimeout(() =>  stateService.go(sessions.state, {application_id}))` for instance.

**Comment by christopherthielen** [comment]
I think this is not a bug.

I think the problem with is when you redirect to `A.B.C`, you're not merging the old parameter values (`{organization_id}`) with the new ones  (`{application_id}`).  When you try to activate `sessions` state, there is no `organization_id`, so the parent state doesn't validate.

The reason it works with a timeout is that `$state.go` [inherits the current parameter values](https://github.com/ui-router/core/blob/adb1fc8a8045fe5b5654c5592b0ddd3272c983f8/src/state/stateService.ts#L269-L273).  The timeout allows the transition to complete, and the [globals object to be updated](https://github.com/ui-router/core/blob/adb1fc8a8045fe5b5654c5592b0ddd3272c983f8/src/globals.ts#L66) with the 
`organization_id` parameter value.

Try using `{ ...trans.params(), application_id }` or `Object.assign({}, trans.params(), { application_id })`

One other potential problem with your approach is that I believe your resolves will be fetched multiple times; once for each new transition.  To avoid this, redirect the transition to the child by returning a `$state.target()` instead of calling `$state.go()`.

```js
return stateService.target(sessions.state, {...trans.params(), application_id});
```

**Comment by FGRibreau** [comment]
Hello @christopherthielen !

Arg, that was one of my initial hypothesis that onEnter was a callback called (too soon) when entering the state and not once the state was ready but since I could not find any other alternative I guessed that onEnter was only called when the current state was done initialized.

Indeed with both the param merging & the return it works! 

This kind of information would profit to everyone in the documentation, I'm surely not the only one doing this ^^. Could you point me to where I should add this kind of information and start a PR for it?

**Comment by FGRibreau** [comment]
@christopherthielen hum, in fact the `return stateService...` generates an error:

```
The transition has been superseded by a different transition
```

**Comment by christopherthielen** [comment]
> Could you point me to where I should add this kind of information and start a PR for it?

What we really need is a new page in the web site's "guides" section that details the lifecycle of a transition.

It's been on my list of things to do, but will have to wait for a bit longer.


> hum, in fact the return stateService... generates an erro

Can you be more specific? If you're returning  `.target()` it shouldn't print a superseded message.  That message isn't necessarily an "error".  It only means that while one transition was still in progress, a new transition was started.  The original transition is cancelled and the new transition supersedes the original one.

**Comment by FGRibreau** [comment]
> What we really need is a new page in the web site's "guides" section that details the lifecycle of a transition.

That would be great yeah!

> If you're returning .target() it shouldn't print a superseded message. That message isn't necessarily an "error". It only means that while one transition was still in progress, a new transition was started. The original transition is cancelled and the new transition supersedes the original one.

Sadly it's considered as an error (and I got an error from it with `.message === "The transition has been superseded by a different transition"`) why not replace this type of information with something else than an error? I was personally misguided by the fact that it was an `Error` I though I did something wrong.

<img width="895" alt="capture d ecran 2017-01-05 00 01 46" src="https://cloud.githubusercontent.com/assets/138050/21662522/58de2e14-d2da-11e6-99e2-78bbc2bfd46c.png">
