### ISSUE TITLE
Resolve names must start with a letter

### ISSUE THREAD

**Issue by Septh** [ui-router/core#20]
_[Foreword: I'm quite lost with the way the repos are organized so my apologies if this is not the right place to post this issue; please redirect me if need be]_

**Using Angular 1.6.1 and U-IRouter 1.0.0-beta3.**

When I was mastering UI-Router legacy, I've made a habit of prefixing my resolves with an underscore character just to make them stand apart in my code. This does not work anymore with UI-Router 1.x.

Try this:

```js
let appState = {
    name: 'app',
    url: '/',
    component: 'app',
    resolve: {
        _currentUser: [ 'auth.service', function(Auth)
        {
            return Auth.getCurrentUser()
        }]
    }
}
$stateProvider.state(appState)

/* ... */

angular.module('myapp').component('app', {
    bindings: {
        _currentUser: '<'
    },
    template: '<pre>{{ $ctrl._currentUser }}</pre>'
})
```

the `<pre>` is empty. 

Now just rename `_currentUser` to `currentUser` (without the underscore) in both the state and component definitions, and it works.

**Comment by Septh** [comment]
Just wanted to add that this is really not a big deal; however it took me some time to figure out so it might be worth mentioning in the docs.

**Comment by christopherthielen** [comment]
Resolve names can start with underscores.  I think this is actually a limitation of angular directive attribute names.  After some digging, I found that directive attributes cannot be prefixed with an underscore, then successfully used.

In the compile function, [attributes are normalized](https://github.com/angular/angular.js/blob/b77defde81fc265c13fa504dc78b41a43997abf4/src/ng/compile.js#L2152) to a camel case string.  The underscore is [considered to be a special character](https://github.com/angular/angular.js/blob/b77defde81fc265c13fa504dc78b41a43997abf4/src/ng/compile.js#L3603-L3614) and the following character is made upper-case during normalization.  Your directive attribute `_currentUser` is normalized to `CurrentUser` instead of `currentUser` like you expected.

If you like, you could open a ticket at https://github.com/angular/angular.js/issues asking that the directive and component registration API throw an error if "illegal" bindings are attempted.
