### ISSUE TITLE
[Future states] add support for pre-loading routes

### ISSUE THREAD

**Issue by aitboudad** [ui-router/core#22]
see https://vsavkin.com/angular-router-preloading-modules-ba3c75e424cb

**Comment by christopherthielen** [comment]
https://github.com/ui-router/core/issues/8 is complete and was released in `ui-router-core` `2.0.0`.

The change landed in `angular-ui-router` `1.0.0-rc.1`.  It should land in the next `ui-router-ng2` release (`1.0.0-beta.4`)

After the initial transition is complete, one simply calls `lazyLoad()` on all the future states:

```
var deregisterHook = $transitions.onSuccess({}, trans => {
  trans.router.stateRegistry.get().filter(state => !!state.lazyLoad).forEach(state => state.lazyLoad())
  deregisterHook();
});
```

Since it's implemented in core, closing this issue.  Feel free to open in https://github.com/ui-router/ng2/issues if you want to track it for ng2 though :)
