### ISSUE TITLE
@uirouter/react 0.8.9 not finding UIRouter

### ISSUE THREAD

**Issue by chargrove** [ui-router/core#471]
Updating @uirouter/react causes error where UIRouter is not defined inside of react state inside angular state.

"@uirouter/react": "0.8.9" works but "@uirouter/react": "0.8.10" does not load when entering "angular.react" state.

Example:
https://stackblitz.com/edit/ui-router-react-hybrid-zsawh1

Error:
> UIRouter instance is undefined. Did you forget to include the <UIRouter> as root component?

**Comment by christopherthielen** [comment]
This issue should really be in the [ui-router/react-hybrid repo](https://github.com/ui-router/react-hybrid/issues), but that's OK.  

I suspect you've got two copies of `@uirouter/react` in your project and they're conflicting (due to different copies of the `UIRouterProvider` object existing).  `@uirouter/react-hybrid` specifies an exact transitive dependency on `@uirouter/react` and that should be all you need (no references to `@uirouter/core` or `@uirouter/angularjs` or `@uirouter/react` in your package.json.

To check if you have two copies, run this command in your project directory.
```
npm list @uirouter/react
```
