### ISSUE TITLE
Any plan for Svelte 3?

### ISSUE THREAD

**Issue by frederikhors** [ui-router/core#475]
Any plan for Svelte 3 (https://svelte.dev/)?

**Comment by nateabele** [comment]
Only whatever plan you have! 😉 Here are the instructions: https://ui-router.github.io/core/docs/latest/

**Comment by christopherthielen** [comment]
FWIW I'm in process of refactoring the view service in core.  This should make it far simpler to implement view plugins (such as svelte) and will also allow for better interop between view technologies (i.e., the hybrid router projects).

**Comment by dalu** [comment]
Hmm, what is the "new view api"?
Is this a very fundamental change?
If one adapts the current state of the library to svelte, how much work would switching to the "new view api" take later?
What are your expectations on how long this migration will take, you're working on right now? 2 months?

**Comment by christopherthielen** [comment]
@dalu 

The "new view api" changes the contract between uirouter core and a view implementation (angular/react/angularjs/sveldte).   If you are interested in implementing a sveldte view plugin, I would try to track the `v7` API rather than code to the current API.  Neither the old nor the new APIs are very well documented, but I think the v7 API is simpler.   I don't expect the API to change much at this point.  

The gist of the refactor is to:

- simplify the api in order to minimize the state and context which a view plugin has to track (move this knowledge into core)
  - implementors should migrate from `registerUIView()` to `registerView()`
- maximize inter-framework compatibility via the new `renderUIViewIntoDivElement` (this will only work in browsers, not server side)

I am about halfway done migrating the react view plugin to the v7 api.  I will be starting on the angularjs and angular ones when react is complete.  Once I've migrated all three (and in doing so, hopefully found flaws or oversights in the new api), I will be publishing the core v7.0.0 API and also publishing new minor versions of the angular/angularjs/react codebases. 

Beyond that, I'd like to:
- write a view plugin guide, for people like yourself
- write a small testing harness for testing that view plugins satisfy the contract
- document a roadmap for the next potential incarnation of ui-router with an intention to make it even friendlier to new frameworks and also to hybrid models (multiple frameworks at the same time).  This would be a major release of all the ui-router incarnations (core/react/angular/angularjs).

Links:

[Core v7 migration WIP](https://github.com/ui-router/core/pull/549/files)
[React migration WIP](https://github.com/ui-router/react/pull/673/files)

**Comment by alexkakhnovskyi** [comment]
> @dalu
> 
> The "new view api" changes the contract between uirouter core and a view implementation (angular/react/angularjs/sveldte). If you are interested in implementing a sveldte view plugin, I would try to track the `v7` API rather than code to the current API. Neither the old nor the new APIs are very well documented, but I think the v7 API is simpler. I don't expect the API to change much at this point.
> 
> The gist of the refactor is to:
> 
> * simplify the api in order to minimize the state and context which a view plugin has to track (move this knowledge into core)
>   
>   * implementors should migrate from `registerUIView()` to `registerView()`
> * maximize inter-framework compatibility via the new `renderUIViewIntoDivElement` (this will only work in browsers, not server side)
> 
> I am about halfway done migrating the react view plugin to the v7 api. I will be starting on the angularjs and angular ones when react is complete. Once I've migrated all three (and in doing so, hopefully found flaws or oversights in the new api), I will be publishing the core v7.0.0 API and also publishing new minor versions of the angular/angularjs/react codebases.
> 
> Beyond that, I'd like to:
> 
> * write a view plugin guide, for people like yourself
> * write a small testing harness for testing that view plugins satisfy the contract
> * document a roadmap for the next potential incarnation of ui-router with an intention to make it even friendlier to new frameworks and also to hybrid models (multiple frameworks at the same time).  This would be a major release of all the ui-router incarnations (core/react/angular/angularjs).
> 
> Links:
> 
> [Core v7 migration WIP](https://github.com/ui-router/core/pull/549/files)
> [React migration WIP](https://github.com/ui-router/react/pull/674/files)

Any progress on this? Thanks
