### ISSUE TITLE
Consider allowing FQN addressing for states w/ `parent:`

### ISSUE THREAD

**Issue by christopherthielen** [ui-router/core#5]
https://github.com/angular-ui/ui-router/issues/3119
https://github.com/ui-router/react/issues/11
https://github.com/angular-ui/ui-router/issues/3181

If the state is defined using `parent:` notation, you cannot reference it by including the parents name.  For example if a state is declared like this:

```js
{
  parent: 'home',
  name: 'foo'
}
```
And you cannot create a sref such as `ui-sref='home.foo'` because home is not technically part of the name of the state.

This also affects glob patterns in transition hooks.  Is not currently possible to match `foo` using this criteria object:
```
{ to: 'home.**' }

**Comment by mfidemraizer** [comment]
IMO, I believe that state paths should be agnostic on how they're defined. It should be a common syntax like CSS selectors.

I've not reviewed the implementation yet, but I guess that the magic is done based on a convention-based engine against state paths. If this is the case, maybe the solution is to turn paths into something that should be parsed, but internally UI router should store everything based on object properties (i.e. using `parent`).

So I think that above approach would guarantee backwards compatibility while providing more power to handle the whole issue scenario. BTW, any code using `parent` instead of a path would be broken. 

Maybe state configuration might define a parameter like `legacy` defaulting to `true`... And/or a service parameter also called `legacy` to define what should be the default value to `legacy` if each state doesn't provide it explicitly...

**Comment by cadilhac** [comment]
Revisiting this issue... Did something changed about globs and dot notation?
