### ISSUE TITLE
Request: Add "check and run immediately" option to transition hook options.

### ISSUE THREAD

**Issue by jonrimmer** [ui-router/core#67]
When registering a transition hook, it is often desirable to run the handler immediately, if the current state matches the criteria. I suggesting adding a new property to ```HookRegOptions``` to do just this. E.g. given...

```ts
transitionService.onSuccess({ to: 'myState.**', () => {
  // Do something
}, { immediate: true });
```

...the handler will be immediately executed if the criteria matches for ```state.current```.

**Comment by christopherthielen** [comment]
I'm going to have to decline this as requested because it doesn't makes sense for all scenarios.  The primary issue is that most transition hooks (onStart, etc) should be able to modify the outcome of a transition (for example, redirecting).  However, if the transition is already complete, then the it cannot be altered.

You can use internal apis to accomplish your goals however.

A [`RegisteredHook` has a `matches()`](https://github.com/ui-router/core/blob/a28b68ab9e731db51ade36e36683d67534788040/src/transition/hookRegistry.ts#L142-L154) function which takes a `TreeChanges`:  

The treechanges object can be retrieved from any `Transition`, for example `router.globals.transition.treeChanges()`.

To [create a `RegisteredHook`](https://github.com/ui-router/core/blob/a28b68ab9e731db51ade36e36683d67534788040/src/transition/hookRegistry.ts#L57-L70) you need the hook type, which is on a private registry on the `TransitionService`:
```
const hookType = $transitions._eventTypes.find(x => x.name === 'onSuccess')
```

It might look something like this (i haven't run nor tested this code)
```
const criteria = { to: 'myState.**' };
const callback = (trans) => { console.log(trans); }

const hookType = $transitions._eventTypes.find(x => x.name === 'onSuccess')
const registeredHook = new RegisteredHook($transitions, hookType, criteria, callback);

if (registeredHook.matches(router.globals.transition)) {
  callback(router.globals.transition);
}
```
