### ISSUE TITLE
Double history replacement with `go(..., {location: 'replace'})` and back/forth buttons

### ISSUE THREAD

**Issue by inad9300** [ui-router/core#77]
This is a (potential) bug report. I'm using Angular 1.6.5 and UI-Router 1.0.6.

I have the following setup:
- Page A: no parameters. No calls to `go()`. Just a reference to test the back/forth behavior.
- Page B: `id` query parameter defined. Uses Component C on its template. The relevant part of the code looks like this:
```typescript
$onInit() {
    const id = getIdMagically()
    if (id !== this.$state.params.id) {
        this.$state.go(this.$state.$current, {id}, {location: 'replace'})
    }
}
```
- Component C: a bunch of query parameters defined (all different than `id`). It does this:
```typescript
$onInit() {
    this.$state.go(this.$state.$current, {/* ... */}, {location: 'replace'})
}
```

And the following occurs (every navigation is done to the routes without parameters, and all followed links contain no parameters):
- Under the workflow: navigate to A, follow a link to B, click back.
  - With the code shown, works. _Expected._
  - When removing the `'replace'` option from B (not C), the two history entries are saved for B, and the back button doesn't work as the user would expect (goes back to B without `id`). _Expected._
- Under the workflow: navigate to B, follow a link to A, follow a link to B, click back.
  - With the code shown, the entry for A is removed from the history, and B appears only once! (To check this, I just hold the click over the back button and look at what Firefox shows, and the entry for A is there first, and then it goes away.) On top of that, this behavior disappears if the navigation starts on A instead of B (so without the first step). _Unexpected._
  - When removing the `'replace'` option from B (not C), one entry is saved in the history for B, another for A, and yet another for B again. This is what the user expects, but I don't understand the behavior from the code. _Unexpected._

If someone had some time to look into this, and either explain to me why it is working the way it is and how to fix it, or fix it in the UI-Router, it would be awesome.

**Comment by christopherthielen** [comment]
I put the app you described into a plunker: http://plnkr.co/edit/SbrscE1oPIkcuEfW9Re0?p=preview
and the easiest way to test it is to download it.

I think what we're seeing is as follows:

When we call `$location.url('/b')` it does not change the URL immediately (it only schedules the URL to be changed).  However, we end up calling `$location.url('/b?id=123')` with `replace` **in the same digest cycle**.  The first URL update `/b` never happened, so the original history entry `/a` is replaced instead.

This I think is a limitation of AngularJS's location handling.  I think a workaround is to use a timeout (so the URL can be set to `/b` and then subsequently replaced with `/b?id=abc`).

Another approach is to use a state based transition hook redirect instead of component based redirects.

```
.onBefore({ to: 'b' }, trans => {
  const params = angular.extend({}, trans.params());
  if (params.id !== 'abc') {
    params.id = 'abc';
    return trans.router.stateService.target(trans.to(), params);
  }
});
```

**Comment by christopherthielen** [comment]
I do think this is a legitimate bug report, but I don't think it is easily fixable due to the AngularJS `$location` service's use of next-digest-cycle-updates.  I would also worry that plugging this hole (working around the $location behavior) might introduce another subtle bug.

**Comment by inad9300** [comment]
Thanks for the time taken, @christopherthielen! I'm sorry to hear about the probable Angular "limitation", and I'll try your workarounds as soon as I have the chance.
