### ISSUE TITLE
Chrome History Incorrect Page Title

### ISSUE THREAD

**Issue by Schlesiger** [ui-router/core#91]
When using Chrome and UI Router the page history shows incorrect titles. For example, let's say I am on page "X", and I navigate to page "Y", my history will show my last page was page "Y". The history will record the title of the page I am navigating to, not the page I am leaving.

I found this [old issue from 2013](https://github.com/angular-ui/ui-router/issues/674) which mentions the same thing in this [demo](https://angular-ui.github.io/ui-router/sample/). The same bug persists in my [demo](https://wallzero.gitlab.io/ui-router-react-digest/) which is using the latest `@uirouter/react`.

The bug persists with `#` or HTML5 routing. I tested on Linux and Windows. It doesn't seem to manifest in Firefox.

**Comment by calebeno** [comment]
We're seeing this issue, too.  Any chance a fix might be possible?

**Comment by elboman** [comment]
We need to make a minimal reproducible setup to narrow down where the problem lies. I just tested out the `@uirouter/react` example in the repo adding `Helmet` to set the page title and everything is working as expected:

![kapture 2017-12-18 at 19 44 47](https://user-images.githubusercontent.com/5050488/34124769-070bc6fa-e42c-11e7-872d-d36a5115a076.gif)

**Comment by elboman** [comment]
@Schlesiger I took a look into your project demo to see what's causing the bug. The problem is this:

You handle the rendering of the UI via redux alone, and even tho the router transitions to another state when clicking a tab button, the UI has already rendered the new tab and the new page title as well. 

In depth: `App` is connected to redux and receives the selected tab index from its state. When the button is pressed you dispatch the redux action which renders the new tab. Upon rendering you receive the new props and you then trigger the router transition which updates the state and the url. So the page title updates before the transition is complete and ui-router picks up the new title when pushing the state in the browser history.

You should let ui-router do the rendering with url parameters and resolves as variables for your tabs, instead of redux, otherwise you skip the router transition rendering order.

An example approach can be: having the selected tab as parameter in the url, and read that value via props (i.e. `this.props.transition.params().tabIndex`) and use that to contionally render the tab content. If you want to update the redux state you can use a transition hook `onFinish`. Otherwise you can use the ui-router/redux plugin that will keeps the transition and router state in you redux state synced. You can take a look here: https://github.com/ui-router/redux

**Comment by elboman** [comment]
@calebeno Basically the problem is how the `render` prop in `UIView` is used.

If you "skip" UIView and pass down props to your routed component that are used to conditionally render something (usually from things like redux state), you end up having the UI controlled by redux in your pages transition instead of the router.

example:
```jsx
// App.js
render () {
	const tabSelected = this.props.tabIndex;
	return (
    	<UIView render={(Comp, props) => <Comp tabSelected={tabSelected} />}
    );
}
```

It should be handled completely by the router otherwise you lose all the goodies that come from transition hooks and logic, and you may end up with different state between router and redux.

Also when using the render props it's important to remember to spread the props that come from `UIView` otherwise you won't find your `resolves` and `transition` injected as props.

example:
```jsx
// App.js
render () {
	return (
    	<UIView render={(Comp, props) => <Comp {...props} />}
    );
}
```

It's important to remember that the render props should be used with caution, usually for things like transition animations. Everything that needs to be passed to the routed component (especially related to navigation) should come as a resolve (or url parameter) from the router. You can even pass the redux state instance and use that to read the state from there.

**Comment by Schlesiger** [comment]
@elboman Thank you for the lengthy response.

This project I have is attempting to predefine initial tab and sidenav/drawer routes - basically to save a lot of repeated boilerplate including html and css and even act as an easy starting ground/sandbox for `@uirouter/react`. I am using Redux in the demo but the library isn't reliant on it; it can be any state manager. A user should be able to setup `ui-router-react-digest` without any knowledge of `@uirouter/react` until they are required to add additional routes.

The reason I am not keen on using buttons with state transitions is because I'd prefer it'd be abstracted. Basically by using state only, a user only needs to pass the tab index and an optional tab component that updates the index. If I use your suggestion, I am worried I would be adding too much additional boilerplate for users, or be requiring too much knowledge of users to get started.

In relation to this ticket; I am still puzzled as to why Firefox doesn't cause an issue. As far as I can tell, using a state manager like component state or Redux isn't the issue. 

I will create a minimal demo in a separate project. Maybe that will help. Please give me a few days to develop and investigate.

**Comment by Schlesiger** [comment]
My apologies for the delay. It has been a busy holiday season.

I have quickly created a second demo project without redux: https://gitlab.com/wallzero/ui-router-react-digest-simple-demo

Here is the demo: https://wallzero.gitlab.io/ui-router-react-digest-simple-demo/

The issue persists. However, it looks like only Firefox works. Chrome, Safari, and IE 11 all share the same issue.

**Comment by Schlesiger** [comment]
I had some more time to investigate the issue and it turns out the title was being updated before the transition completed. Before I was relying on the component rendering via [react-document-title](https://www.npmjs.com/package/react-document-title). I didn't realize `render()` and the component tree could update before or in parallel to the state transition. It is also strange that Firefox and Chrome would exhibit different behaviors.

Now I am using the `transitionService.onSuccess` hook. `resolve()` could also be used but isn't applicable in this use case.
